openapi: 3.1.0
info:
  title: Water Remediation Line Items API
  version: 1.0.0
servers:
  - url: https://api.example.com  # placeholder for GPT to accept spec
paths:
  /line-items:
    get:
      summary: Retrieve water remediation line items
      operationId: getLineItems
      responses:
        '200':
          description: A list of line items
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/$defs/LineItem'
                examples:
                  sample:
                    summary: Example line items
                    value:
                      - category_code: WTR
                        selector_code: ACT
                        description: Remove wet ceiling tile & drywall and bag for disposal
                        unit: SF
                        cost: "$1.34"
                      - category_code: WTR
                        selector_code: ACT3
                        description: Remove wet ceiling tile & drywall and bag - Cat 3
                        unit: SF
                        cost: "$1.96"
                      - category_code: WTR
                        selector_code: BASE
                        description: Tear out baseboard
                        unit: LF
                        cost: "$0.58"
                      - category_code: WTR
                        selector_code: BARRF
                        description: Containment Barrier - air filter
                        unit: EA
                        cost: "$14.36"
                      - category_code: WTR
                        selector_code: BAG
                        description: Plastic bag - used for disposal of contaminated materials
                        unit: EA
                        cost: "$3.02"

$defs:
  LineItem:
    type: object
    properties:
      category_code:
        type: string
        description: The code for the service category (e.g., WTR)
      selector_code:
        type: string
        description: The internal selector or pricing code
      description:
        type: string
        description: Description of the remediation work
      unit:
        type: string
        description: Unit of measure (e.g., SF, LF, EA)
      cost:
        type: string
        description: The price of the line item
    required:
      - category_code
      - selector_code
      - description
      - unit
      - cost
